### ISSUE TITLE
dataset source

### ISSUE THREAD

**Issue by liboliba** [finlytics-hub/churn_model-survival-analysis#1]
Hello there,
From the blog it says the dataset is publicly available. But this seems to self-referencing and where the dataset originally collected? I'm developing academic work and hope to site the data.

Thanks & regards

**Comment by finlytics-hub** [comment]
Hi there,

The dataset can be found [here](https://www.kaggle.com/blastchar/telco-customer-churn) and [here](https://github.com/treselle-systems/customer_churn_analysis/blob/master/WA_Fn-UseC_-Telco-Customer-Churn.csv).

Hope it helps.
